### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by tefygz** [jina-ai/dashboard#224]
In the ActionButton component, are the colors hard-coded?

**Comment by BastinJafari** [comment]
Hey @tefygz,
you mean the styled.button component in HubOverviewAction.tsx?
We use emotions theming for applying colors.

https://emotion.sh/docs/theming

The themes are in src/theme.ts

**Comment by Roshanjossey** [comment]
Hi @tefygz, one of the colors was hardcoded in ActionButton. This is now fixed with https://github.com/jina-ai/dashboard/pull/231.

If you're interested in working on issues like that, please check the issue https://github.com/jina-ai/dashboard/issues/209. or reach out to us. There are more css classes that we want to refactor into emotion style.
