### ISSUE TITLE
Dashboard plot does not match with yaml file

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#268]
Dashboard plot does not match with yaml file (helloworld multimodal's flow-index.yml)**Describe the bug** helloworld multimodal's flow-index.yml does not show correctly once pasted to Jina Dashboard **Have you solved it? If so, let us know how!** --- **Environment** **Screenshots and logs**

<p></p>

<https://github.com/jina-ai/dashboard/issues/266>

![](https://user-images.githubusercontent.com/22567795/111725142-7a6ce080-88a1-11eb-882c-34fee6045f4b.png)

<p></p>

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7392735

**Comment by franquil** [comment]
Hi @lusloher , I wonder what the correct Dashboard plot should be for that file. It would be helpful to verify what caused the issue exactly before solving it.

**Comment by aga11313** [comment]
This was closed due to inactivity.

We discussed this issue with the engineering and this seems to be a feature of the dashboarding framework we are using and not strictly a bug. Since Flows like this will be really unlikely in real Jina usecase scenarios I am going to leave this closed for the moment.
